### ISSUE TITLE
Branch protection for master

### ISSUE THREAD

**Issue by timoweiss** [timoweiss/collector-backend#4]
Wäre es für dich ok @Fingu wenn ich die master branch protecte und wir mit pull requests arbeiten? 
Dann kann jeweils der andere das geänderte reviewen und jeder weiß bescheid was geändert wurde :)

**Comment by jfinckh** [comment]
Ja klar :)
werde vermutlich eh nichts ändern müssen und wenn doch hätte ich auch so nochmal Bescheid gegeben, die Änderung heute morgen war aber so klein ( "host" -> "collector_host" in nem kommentar) dass ich das direkt gemacht habe :D

**Comment by timoweiss** [comment]
no problemo :) änderungen/fixes sind immer willkommen ;)
