### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by jfinckh** [timoweiss/collector-backend#5]
Hey, habe doch nochmal eine Frage und hoffe dass ich dich dann endlich in Frieden lassen kann :D 

Ich versuche in einer Expressapp die Metriken aus dem Backend zu holen, dafür habe ich eine kleine Loginmaske die nach dem einloggen vom Backend auch einen korrekten Response zurück bekommt. Nun wollte ich die in einen cookie speichern und wenn ich z.B. einen get-request auf /services   mache den cookie mitschicken. Irgendwie bekomme ich aber immer 
`{"statusCode":400,"error":"Bad Request","message":"Invalid cookie header"}` zurück :(

Was mache ich schon wieder falsch? :D 

Loginmaske:
```
        request.post(
            'http://localhost:2020/users/login',
            { json: {
                mail: req.body.email,
                password: req.body.pw
            } },
            function (error, response, body) {
                if (!error && response.statusCode == 200) {
                    var buf = new Buffer(JSON.stringify(body), 'utf-8'); 
                    zlib.gzip(buf, function (_, result) {  
                        res.cookie("monitor",result);                   
                        res.send(body);
                    });
                }
            }
        );
```

wo ich die systeme holen möchte:

```
    request({url: 'http://localhost:2020/systems',
                headers: {
                    Cookie: req.cookies,
                    'Content-Type': 'application/json',
                    'Content-Length': Buffer.byteLength(req.cookies,'utf8')
                }
            },
            function(error, response, body) {
                if (!error && response.statusCode == 200) {
                     res.send(body);
                }else{
                    res.send(body)
                }
    });
```

Speicher ich hier überhaupt das richtige in meinen cookie? 

Sorry dass ich dich schon wieder nerve :/

**Comment by timoweiss** [comment]
Ich frage mal nicht nach dem grund für die express app :D
Was steht denn in `req.cookies` drin?

**Comment by jfinckh** [comment]
Haha :D Taugt express nichts? :D

Da steht das drin: 
```
{ monitor: 
   { type: 'Buffer',
     data: 
      [ 31,
        139,
        8,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        171,
        86,
        138,
        207,
        76,
        81,
        178,
        82,
        50,
        181,
        48,
        73,
        74,
        54,
        55,
        51,
        51,
        73,
        77,
        52,
        54,
        55,
        48,
        54,
        51,
        52,
        ... ] } }
```

**Comment by timoweiss** [comment]
hm, ich bin nicht so der fan von. aber ich weiß auch nicht was du vor hast. aber hört sich an als würdest du eine api auf die api bauen?
aber dein `request` ist doch sicher https://github.com/request/request oder? Ich weiß nicht genau ob das die richtige value dafür ist.
könnte sein, dass es in etwa so aussehen muss:
```javascript
 request({url: 'http://localhost:2020/systems',
                headers: {
                    Cookie: "monitor=someStringValue;somethingElse=value;sometingReallyElse=value" 
                }
            },
            function(error, response, body) {
                if (!error && response.statusCode == 200) {
                     res.send(body);
                }else{
                    res.send(body)
                }
    });
```

ich denke das bekommst du wenn du `toString()` auf `req.cookies.monitor.data` aufrufst. Also in etwa:
```javascript
const myCookieValues = 'monitor=' + req.cookies.monitor.data.toString();
request({
    url: 'http://localhost:2020/systems',
    headers: {
        Cookie: myCookieValues
     }
}, (error, response, body)=>{...})
```

**Comment by jfinckh** [comment]
Hatte noch nie was mit node.js und co zu tun und bin über express gestolpert und dachte ich versuch das mal, hab aber keinen Vergleich :D  

Ja so im Prinzip schon, soll so Schnittstelle zwischen Backend und Frontend werden, wobei das Frontend ein grafischer Editor in dem MDSD-tool Zeta von der Htwg sein soll. Also halt hauptsächlich bisschen mappen und kategorisieren und dann weiterleiten, ggfls neue Services starten, .. 

Genau der request :)  Habe deinen Vorschlag gerade versucht, der `Invalid Cookie Header` ist weg, dafür bekomme ich `{"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}` :/ 

Passt das überhaupt, dass ich den response body nach dem Login einfach gzippe und in einen cookie schreibe? Wenn ich mir den Cookie anschau den es bei der Swagger-doku anlegt und den den ich anlege haben die einen ganz anderen Inhalt :D 

"Mein" Cookie: 
`j%3A%7B%22type%22%3A%22Buffer%22%2C%22data%22%3A%5B31%2C139%2C8%2C0%2C0%2C0%2C0%2C0%2C0%2C3%2C171%2C86%2C138%2C207%2C76%2C81%2C178%2C82%2C50%2C181%2C48%2C73%2C74%2C54%2C55%2C51%2C51%2C73%2C77%2C52%2C54%2C55%2C48%2C54%2C51%2C52%2C78%2C54%2C50%2C51%2C54%2C73%2C83%2C210%2C81%2C202%2C77%2C204%2C204%2C1%2C170%2C40%2C73%2C45%2C46%2C113%2C0%2C17%2C186%2C25%2C37%2C229%2C233%2C122%2C41%2C169%2C64%2C169%2C188%2C196%2C220%2C84%2C160%2C148%2C91%2C102%2C94%2C114%2C118%2C6%2C144%2C95%2C92%2C90%2C4%2C21%2C242%2C202%2C207%2C72%2C204%2C203%2C75%2C45%2C6%2C10%2C22%2C20%2C228%2C36%2C230%2C1%2C133%2C146%2C18%2C139%2C51%2C147%2C193%2C230%2C85%2C4%2C87%2C22%2C151%2C164%2C230%2C22%2C43%2C89%2C25%2C214%2C2%2C0%2C18%2C37%2C64%2C116%2C129%2C0%2C0%2C0%5D%7D`

Swagger-Cookie:

`Fe26.2**7a13ffac06e74ea260e5f58be6111036b126362ac25819ddc8ed1a1b5b410182*6ULuSm3XnRltkdYwAmzSWA*-eHsEiolGTezKO9G-9khilYkphdQWa9i3JQwsNjJP3peLEiGhAUrl9PhU3Ly5KTV0wVRBZwni1v6WFrnhFlu0JeRf01qYyN2TNxxjFhgkfS3m6TYO1ngYpPwgKVSQVjQlDNl2WWCX3qHNtbqZfoYT2EjqUomMb_li2-7XcjMI2xqQ6VEUsg0dNVTaqRmGnfO**85384040c1a19b0f09b52e22180d82e4afffd2f8c40c8fee1ae6608bcc0fd4eb*NLTPENg_L6hafpAem5ucvz5aQz4gbmiDdNJmF6ydR_w`

**Comment by jfinckh** [comment]
Ok, gzip war kompletter bullshit, allgemein dass ich den response-body in den cookie gehauen hab war minder-schlau, [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie) schickt beim login ja schon einen mit [iron](https://github.com/hueniverse/iron) verschlüsselten cookie zurück.. Mit dem mit iron verschlüsselten Cookie läuft es dann doch :D 

Sorry für die dumme Frage  :D
